iasql/iasql

src/modules/aws_vpc@0.0.1/index.ts, test/modules/aws-vpc-integration.ts
=> Fix the aws_vpc sync bug

README.md, test/modules/aws-vpc-integration.ts
- Try to fix the VPC test. This is super-poorly documented on AWS's part
- Make absolutely sure we're attaching the subnet to the right vpc record
=> Fix the VPC tests

src/modules/aws_account@0.0.1/index.ts, src/modules/aws_cloudwatch@0.0.1/index.ts, src/modules/aws_ec2@0.0.1/index.ts, src/modules/aws_ecr@0.0.1/index.ts, src/modules/aws_ecs_fargate@0.0.1/index.ts, src/modules/aws_elb@0.0.1/index.ts, src/modules/aws_rds@0.0.1/index.ts, src/modules/aws_security_group@0.0.1/index.ts, src/modules/aws_vpc@0.0.1/index.ts, src/modules/interfaces.ts, src/services/iasql.ts
=> Implicit migration definition

src/modules/aws_account@0.0.1/index.ts, src/modules/aws_cloudwatch@0.0.1/index.ts, src/modules/aws_ec2@0.0.1/index.ts, src/modules/aws_ecr@0.0.1/index.ts, src/modules/aws_ecs_fargate@0.0.1/index.ts, src/modules/aws_elb@0.0.1/index.ts, src/modules/aws_rds@0.0.1/index.ts, src/modules/aws_security_group@0.0.1/index.ts, src/modules/aws_vpc@0.0.1/index.ts, src/modules/interfaces.ts
Resolves #475
Disappointed that this only dropped about half of the db mappers. Automatically figuring out relations to include should tackle most of the rest, but a few are very peculiar and would require a lot more effort to replace.
=> Automate generation of the db mapper for trivial situations.

.github/dependabot.yml, yarn.lock
Dependabot is gonna be useless if we just ignore it all the time, so let's reduce the frequency (but also get these new PRs closed out)
=> Update the yarn lockfile again, but shut it up for a little while, at least

src/router/db.ts, src/services/iasql.ts
- get uid from req.user
- fix export after metarepo refactor + ignore iasql_* tables
=> fix export after metarepo refactor + ignore `iasql_*` tables

src/migration/1647526647810-init.ts
taken from https://aws.amazon.com/blogs/database/migrating-oracle-autonomous-transactions-to-postgresql/
=> reuse dblink connection within the same session

src/migration/1647526647810-init.ts, src/services/db-manager.ts
=> Fix the regular user calling the iasql_ funcs and demonstrate a nicer install

sql/create_fns.sql, sql/drop_fns.sql, src/entity/operation.ts, src/migration/1648258958089-init.ts, src/modules/aws_account@0.0.1/index.ts, src/modules/aws_cloudwatch@0.0.1/index.ts, src/modules/aws_ec2@0.0.1/index.ts, src/modules/aws_ecr@0.0.1/index.ts, src/modules/aws_ecs_fargate@0.0.1/index.ts, src/modules/aws_elb@0.0.1/index.ts, src/modules/aws_rds@0.0.1/index.ts, src/modules/aws_security_group@0.0.1/index.ts, src/modules/aws_vpc@0.0.1/index.ts, src/modules/interfaces.ts, src/services/iasql.ts, src/services/scheduler.ts, test/modules/aws-account-integration.ts
=> Improve the UX of the remaining iasql_ functions

src/services/iasql.ts
=> `snake_case` the table names

sql/create_fns.sql, src/router/db.ts, test/helpers.ts
this has been very useful to clean up my own account when testing the quickstart for https://github.com/iasql/ecs-fargate-examples/issues/11
=> delete all records fn

src/modules/aws_security_group@0.0.1/index.ts, src/services/iasql.ts, test/modules/aws-security-group-integration.ts
=> `aws_security_group` flakiness fix

sql/create_fns.sql, src/services/iasql.ts, test/modules/aws-cloudwatch-integration.ts, test/modules/aws-ec2-integration.ts, test/modules/aws-ecr-integration.ts, test/modules/aws-ecs-integration.ts, test/modules/aws-elb-integration.ts, test/modules/aws-rds-integration.ts, test/modules/aws-security-group-integration.ts, test/modules/aws-vpc-integration.ts
Resolves #578
Will need work once we actually have modules with multiple versions, but how we're gonna support that is still a bit up in the air, anyways.
=> Make module versions optional on install/uninstall

sql/create_fns.sql, test/modules/aws-security-group-integration.ts
=> Fix the install and uninstall reporting when modules are referenced without versions

src/services/logger.ts, src/services/scheduler.ts
=> Return error metadata

src/services/logger.ts, src/services/scheduler.ts
This reverts commit 7b7ec7845f12586696451d2c2c510245eb4b2a71.
=> Revert "Return error metadata (#598)"

src/modules/aws_ec2@0.0.1/index.ts
Resolves #606 since the other part was ruled out as actually not a bug.
=> EC2 update is actually replace only

src/modules/aws_ec2@0.0.1/entity/instance.ts, src/modules/aws_ec2@0.0.1/index.ts, src/modules/aws_ec2@0.0.1/migration/1649361429307-aws_ec2.ts, src/services/gateways/aws.ts
=> Add Keypair support to EC2 module

src/scripts/module-json-utils.ts
I can't believe I missed this earlier
=> Bugfix for gen-module

src/services/gateways/aws.ts, test/modules/aws-elb-integration.ts
=> Wait for LoadBalancer to be fully terminated

src/modules/aws_ecs_fargate@0.0.1/index.ts
Resolves #642 
Before: 
After:
=> Custom error on empty container definition list

src/modules/aws_security_group@0.0.1/entity/index.ts, src/modules/aws_security_group@0.0.1/index.ts, src/modules/aws_security_group@0.0.1/migration/1649780529212-aws_security_group.ts, src/modules/aws_security_group@0.0.1/module.json, test/common/total-failure.ts, test/modules/aws-ec2-integration.ts, test/modules/aws-elb-integration.ts, test/modules/aws-rds-integration.ts, test/modules/aws-security-group-integration.ts, test/modules/aws-vpc-integration.ts
=> Fix VPC mutation

src/modules/aws_vpc@0.0.1/entity/index.ts, src/modules/aws_vpc@0.0.1/migration/1649845176247-aws_vpc.ts
Cannot duplicate values:
Still having multiple nulls available:
=> Add vpc_id unique index if not null

src/modules/iasql_functions@0.0.1/sql/create_fns.sql, test/sql/delete_records.sql
=> Update delete fns to ignore vpc and subnets

package.json, src/services/scheduler.ts, src/services/typeorm.ts, yarn.lock
Resolves #718
We weren't ever trying to re-acquire these names in a different context, and had been putting randomness into the names already, so let's just make them effectively impossible to collide.
=> UUID the connection names

src/services/iasql.ts, src/services/scheduler.ts
=> Wait for the Graphile workers to actually stop during disconnect

package.json, src/config/config.ts, src/config/production.ts, src/config/staging.ts, src/services/logger.ts, yarn.lock
The log ingestion key is not considered a secret, it only allows writing logs, but I can rotate this key and we can make it a secret instead if desired.
=> Add LogDNA logging to staging and production

src/services/scheduler-api.ts
I realized when running locally that it kept spawning new child processes, because the scheduler child process would eventually pull in a dependency on itself and it would try to init a child process, and so on. This prevents that cycle from going on forever and should reduce the memory consumption issue.
=> Only spawn one child proc

src/cloudformation/iasqlConnectTemplate.yaml
=> Migrate lambda caller from python to js

src/modules/0.0.6/iasql_functions/sql/create_fns.sql, src/modules/0.0.6/iasql_functions/sql/drop_fns.sql
=> Add iasql_version function

src/modules/0.0.6/aws_ecr/index.ts, src/modules/0.0.6/aws_ecs_fargate/index.ts, src/modules/0.0.6/aws_elb/index.ts, src/services/gateways/aws.ts, test/helpers.ts, test/modules/aws-ecs-ecr-integration.ts
=> Make ECS tests more stable and reduce execution times

src/modules/0.0.8/iasql_functions/sql/create_fns.sql, src/services/iasql.ts, test/common/total-failure.ts
=> Make iasql_upgrade return a value instead of only communicate via error messages

src/config/ci.ts, src/config/config.ts, src/config/local.ts, src/config/production.ts, src/config/staging.ts, src/config/test.ts, src/router/index.ts, src/services/iasql.ts
Also fix one of the crashes I saw last night
=> Add REST endpoint to get the oldest supported version

src/services/gateways/aws_2.ts
I'm sorry I missed this in a past review.
=> No hot-loop to sleep. Use promises instead

src/router/db.ts, src/services/logger.ts, src/services/scheduler.ts, test/helpers.ts
=> Fix empty error logs

src/modules/0.0.10/aws_account/index.ts, src/modules/0.0.10/aws_acm_import/index.ts, src/modules/0.0.10/aws_acm_list/index.ts, src/modules/0.0.10/aws_cloudwatch/index.ts, src/modules/0.0.10/aws_ec2/index.ts, src/modules/0.0.10/aws_ec2_metadata/index.ts, src/services/aws_macros.ts
=> Part 1: Macro-ify AWS client usage

.github/workflows/ci.yml, src/modules/0.0.11/aws_ec2/entity/instance.ts, src/modules/0.0.11/aws_ec2/index.ts, src/modules/0.0.11/aws_ec2/migration/1656581121109-aws_ec2.ts, src/modules/0.0.11/aws_ec2/module.json, test/modules/aws-ec2-integration.ts
=> `aws_ec2` + `aws_vpc` integration

src/modules/0.0.11/aws_ecs_simplified/aws.ts, src/modules/0.0.11/aws_ecs_simplified/cloud_create_fns.ts, src/modules/0.0.11/aws_ecs_simplified/cloud_delete_fns.ts, src/modules/0.0.11/aws_ecs_simplified/cloud_fns.ts, src/modules/0.0.11/aws_ecs_simplified/index.ts
I cannot figure out what subtle bug I introduced in the rewrite with the macro functions, but I don't want to delay deprecation of the centralized gateway
=> Subsume a copy of the gateway in the ECS simplified module

src/modules/0.0.12/aws_security_group/entity/index.ts, src/modules/0.0.12/aws_security_group/migration/1657233581054-aws_security_group.ts, src/modules/0.0.12/aws_security_group/migration/1657301748333-aws_security_group.ts
=> Guarantee uniqueness of the Security Group names

package.json, src/modules/0.0.12/aws_iam/index.ts, test/modules/aws-iam-integration.ts, yarn.lock
=> Fix `aws_iam` role policy comparison

src/modules/0.0.12/aws_ec2/index.ts, src/modules/0.0.12/aws_vpc/index.ts, test/modules/aws-vpc-integration.ts
This should hopefully resolve the E2E test failure we saw last night, but can only confirm after this is merged
=> Make the AvailabilityZone records quasi-immutable

package.json, src/modules/index.ts, src/services/db-manager.ts, src/services/iasql.ts, src/services/typeorm.ts, yarn.lock
Part of the work to make version bumping fully automated is for the code to automatically determine which versions should even be loaded.
=> Auto-import module versions

.github/workflows/ci.yml, .github/workflows/main.yml, rfcs/000 - RFC Template.md
=> RFC template

src/services/scheduler.ts, src/services/typeorm.ts
This PR will probably only be deployed to staging to help me figure out the issue (since I can't reproduce locally)
=> Filter out unsupported databases from the bootstrapping process

.github/workflows/develop.yml, .github/workflows/drop.yml, .github/workflows/version.yml
They were missing a git account to execute as.
=> Fix the development github actions

src/modules/0.0.14/aws_vpc/index.ts
Modify vpc creation to wait until state is available.
Also modify method equality to check for cidr, state
and default.
Closes-Issue: #722
=> Issue #722: Wait for vpc to be created

src/modules/0.0.14/aws_vpc/index.ts, test/modules/aws-vpc-integration.ts
Include a restore method, that reverses the changes on
vpc state. Include relevant tests for create/update.
Closes-Issue: #722
=> Issue #722: Add restore method, and update tests

src/modules/0.0.14/aws_vpc/entity/vpc.ts, src/modules/0.0.14/aws_vpc/index.ts, src/modules/0.0.14/aws_vpc/migration/1658328076929-aws_vpc.ts, test/modules/aws-vpc-integration.ts
Include adding and updated tags
Resolves #1019
=> Issue #1019: Add support for tags at vpc module

src/modules/0.0.14/aws_elb/migration/1655822977761-aws_elb.ts, src/modules/0.0.14/aws_elb/sql/create_custom_constraints.sql, src/modules/0.0.14/aws_elb/sql/drop_custom_constraints.sql, src/modules/0.0.14/aws_elb/sql/index.ts
=> Add a check function to validate the load balancer's availability zones list

src/services/iasql.ts, test/modules/aws-account-integration.ts
=> Better iasql_* function error handling on unsupported database versions

src/modules/0.0.14/aws_elb/entity/load_balancer.ts, src/modules/0.0.14/aws_elb/sql/create_custom_constraints.sql, src/modules/0.0.14/aws_elb/sql/drop_custom_constraints.sql, test/modules/aws-ecs-ecr-integration.ts
=> Load balancer + Subnet

.develop.sh, .drop.sh
Advisory, going to land no matter what: actually add the config changes to the commit
=> One more script fix

.drop.sh
Also advisory, need to run it on `main` to be sure
=> Fix the drop script

src/modules/0.0.15/aws_s3/index.ts, test/modules/aws-s3-integration.ts
Once the bucket policy coverage has been added, add specific
testing for the use case of adding a policy on bucket creation.
Also perform some refactor of utils and mappers.
Resolves #1044
=> Issue #1044: Cover bucket policy on creation

package.json, src/lib.d.ts, src/router/db.ts, src/services/iasql.ts, test/modules/aws-account-integration.ts, yarn.lock
=> Execute each statement in a multi-statement query in a separate connection to avoid data race issues

src/modules/0.0.15/aws_vpc/index.ts
=> Handle invalid elastic ips on nat gateways

test/modules/aws-ec2-integration.ts
=> Handle ec2 test flaky insuficient capacity issue

src/services/iasql.ts
Apparently Postgres' GRANT and REVOKE are not concurrent-safe. See this discussion: https://www.postgresql.org/message-id/3473.1393693757%40sss.pgh.pa.us
While reducing the number of temporary accounts needed to function is the better long-term plan, this weird `do-try-catch-while` loop lets us quasi-linearize across requests without *too* much contention and prevent request failures from reaching the users.
=> `do` `try` to `catch` `while` we're `await`ing for the temporary postgres user

package.json, src/modules/0.0.16/aws_secret/entity/index.ts, src/modules/0.0.16/aws_secret/entity/secret.ts, src/modules/0.0.16/aws_secret/index.ts, src/modules/0.0.16/aws_secret/migration/1659546319970-aws_secret.ts, src/modules/0.0.16/aws_secret/migration/1659632487550-aws_secret.ts, src/modules/0.0.16/aws_secret/module.json, src/modules/0.0.16/index.ts, src/services/aws_macros.ts, test/modules/aws-secret-integration.ts, yarn.lock
It offers the possibility of creating secrets, modifying
secret description and secret value, and removing the
secret
=> Issue #1037: Add module for secrets

src/modules/0.0.17/aws_dynamo/index.ts
=> Class-ify 'aws_dynamo'

src/modules/0.0.17/aws_elasticache/index.ts
I was going to refactor this module, but there was a lot of dead code (functions and arguments) and a function "color" mistake, so I decided to make those cleanup changes in a separate PR before refactoring this module. Will come back to refactor it after this PR is merged.
=> Remove unused elements from Elasticache module

src/modules/0.0.17/aws_acm_import/index.ts
=> Class-ify 'aws_acm_import'

src/modules/0.0.17/aws_acm_import/index.ts, src/modules/0.0.17/aws_acm_list/index.ts, src/modules/0.0.17/aws_elb/index.ts, src/modules/interfaces.ts
=> Class-ify 'aws_acm_list'

src/modules/0.0.17/aws_cloudwatch/index.ts, src/modules/0.0.17/aws_ecs_fargate/index.ts
=> Class-ify 'aws_cloudwatch'

package.json, src/modules/0.0.17/aws_lambda/index.ts, src/modules/interfaces.ts
Also eliminate the need to import the `module.json` file manually just to attach the dependencies.
=> Class-ify 'aws_lambda'

src/modules/0.0.17/aws_secrets_manager/index.ts
- Could have sworn I did this already
- Class-ify 'aws_secrets_manager'
=> Class-ify 'aws_secrets_manager'

.github/workflows/module-cleanup.yml
This job is getting stuck sometimes initializing the engine. Let's add a timeout, for now, to avoid endless runnings while it is addressed properly
=> Clean up timeout

src/entity/index.ts, src/migration/1660750886984-upgrading-flag.ts, src/services/iasql.ts, src/services/repositories/metadata.ts
=> Block most operations during an upgrade

src/modules/0.0.18/aws_secrets_manager/index.ts
Tests are failing quite often on secret deletion, which indicates
that the query may take more time to perform. Implement a wait/retry
logic, until secret does not exist anymore.
Closes #1161
Issue #1161: Retry on delete secret command
Tests are failing quite often on secret deletion, which indicates
that the query may take more time to perform. Implement a wait/retry
logic, until secret does not exist anymore.
Closes #1161
=> Issue #1161: Retry on delete secret command

src/modules/0.0.19/iasql_platform/entity/index.ts, src/services/iasql.ts, test/common/total-failure.ts
Is this all that's wrong with uninstall?
=> Fix the uninstall logic

src/modules/0.0.19/aws_security_group/entity/index.ts, src/modules/0.0.19/aws_security_group/migration/1662052010605-aws_security_group.ts
Removed the nullable option on aws_security_group description
=> removed nullable option on aws_security_group description

docs/docs/concepts/apply-and-sync.md, docs/docs/sample-queries/aws_ec2.md, docs/docs/sample-queries/aws_vpc.md
also add a bit about `preview_*` functions
=> [docs] explicitly use default vpc in ec2 sample query

test/helpers.ts
In order to generate a private key, first try to take
the content from the generated openssl command. If it
does not exist, fallback to privkey content
Closes #1220
=> fix: take cert from stdout if it exist

src/services/iasql.ts, src/services/scheduler-api.ts, src/services/scheduler.ts
This reverts commit c3262f011938bf8628cf64aad6ce9af1c0e9ae7a.
=> Revert "Refactor Scheduler functions and add Sentry error logging (#1182)"

.github/workflows/ci.yml
And open https://github.com/iasql/iasql-engine/issues/1308
=> do not show coverage for integration tests

.github/workflows/django.yml, .github/workflows/prisma.yml, examples/ecs-fargate/prisma/infra/index.js, src/modules/0.0.21/aws_codebuild/sql/after_install.sql, src/scripts/setup-iasql-db.sh, test/modules/aws-codebuild-integration.ts, test/tutorials/django-ci.sh, test/tutorials/prisma-ci.sh
Fixes being tested:
- `generate_put_ecr_image_build_spec` util function
- Prisma queryRaw invocation
=> Run tutorial integration tests on every CI run

src/modules/0.0.21/aws_ecr/index.ts, test/modules/aws-ecr-integration.ts
Pushing twice to `<repositoryuri>:latest` but with different content:
=> handle untagged images case on ecr

src/modules/0.0.22/aws_acm_import/entity/certificate_import.ts, src/modules/0.0.22/aws_acm_import/migration/1666174447169-aws_acm_import.ts, src/modules/0.0.22/aws_acm_import/sql/after_install.sql, src/modules/0.0.22/aws_acm_import/sql/before_uninstall.sql, src/modules/0.0.22/aws_api_gateway/entity/api.ts, src/modules/0.0.22/aws_api_gateway/migration/1666174657614-aws_api_gateway.ts, src/modules/0.0.22/aws_api_gateway/sql/after_install.sql, src/modules/0.0.22/aws_api_gateway/sql/before_uninstall.sql, src/modules/0.0.22/aws_appsync/entity/graphql_api.ts, src/modules/0.0.22/aws_appsync/migration/1666174822997-aws_appsync.ts, src/modules/0.0.22/aws_appsync/sql/after_install.sql, src/modules/0.0.22/aws_appsync/sql/before_uninstall.sql, src/modules/0.0.22/aws_cloudwatch/entity/log_group.ts, src/modules/0.0.22/aws_cloudwatch/migration/1666174979986-aws_cloudwatch.ts, src/modules/0.0.22/aws_cloudwatch/sql/after_install.sql, src/modules/0.0.22/aws_cloudwatch/sql/before_uninstall.sql, src/modules/0.0.22/aws_dynamo/entity/index.ts, src/modules/0.0.22/aws_dynamo/migration/1666175118698-aws_dynamo.ts, src/modules/0.0.22/aws_dynamo/sql/after_install.sql, src/modules/0.0.22/aws_dynamo/sql/before_uninstall.sql, src/modules/0.0.22/aws_elasticache/entity/cache_cluster.ts, src/modules/0.0.22/aws_elasticache/migration/1666175240591-aws_elasticache.ts, src/modules/0.0.22/aws_elasticache/sql/after_install.sql, src/modules/0.0.22/aws_elasticache/sql/before_uninstall.sql, src/modules/0.0.22/aws_secrets_manager/entity/secret.ts, src/modules/0.0.22/aws_secrets_manager/migration/1666175378522-aws_secrets_manager.ts, src/modules/0.0.22/aws_secrets_manager/sql/after_install.sql, src/modules/0.0.22/aws_secrets_manager/sql/before_uninstall.sql
=> Standardize region decorators

examples/ecs-fargate/prisma/infra/artifacts/buildspec.yml
=> fix: include sample buildspec.yml to consume from codepipeline

src/modules/0.0.22/aws_acm_import/index.ts, src/modules/0.0.22/aws_ec2/mappers/general_purpose_volume.ts, src/modules/0.0.22/aws_ec2/mappers/instance.ts, src/modules/0.0.22/aws_ec2/mappers/registered_instance.ts, src/modules/0.0.22/aws_ec2_metadata/index.ts, src/modules/0.0.22/aws_ecr/index.ts, src/modules/0.0.22/aws_elb/index.ts, src/modules/0.0.22/aws_memory_db/mappers/memory_db_cluster.ts, src/modules/0.0.22/aws_rds/index.ts, src/modules/0.0.22/aws_route53_hosted_zones/index.ts, src/modules/0.0.22/aws_security_group/index.ts, src/modules/0.0.22/aws_vpc/mappers/endpoint_gateway.ts, src/modules/0.0.22/aws_vpc/mappers/nat_gateway.ts, src/modules/0.0.22/aws_vpc/mappers/subnet.ts, src/modules/interfaces.ts
=> Helper to generate ids + standardize read calls with composite ids

src/modules/0.0.22/iasql_functions/iasql.ts
=> Soft-disable the `aws_code*` modules

src/modules/0.0.22/aws_vpc/entity/endpoint_interface.ts, src/modules/0.0.22/aws_vpc/mappers/endpoint_gateway.ts, src/modules/0.0.22/aws_vpc/mappers/endpoint_helpers.ts, src/modules/0.0.22/aws_vpc/mappers/endpoint_interface.ts, src/modules/0.0.22/aws_vpc/migration/1667551443085-aws_vpc.ts, src/modules/0.0.22/aws_vpc/migration/1667590922115-aws_vpc.ts, test/modules/aws-vpc-integration.ts
=> feat: add additional services to endpoint interface

README.md
Signed-off-by: Yolanda Robla <yolanda@iasql.com>
=> fix: update coverage and add missing links

site/blog/2021/intro.mdx, site/blog/2022/open-source.mdx
and more amenable to git if we need to do date changes
=> cleaner naming convention for blog post files

.github/workflows/ci.yml
It has been affecting the `aws_ecs_simplified` test... Let's increase the timeout to 90 min, monitor the test and adjust the timeout in follow-up PR.
=> Increase test timeout

src/modules/0.0.23/aws_ec2/mappers/instance.ts, test/modules/aws-ec2-integration.ts
=> fix: check if sg exist before creating the vm, retry if not

.github/workflows/ci.yml
@mtp1376 sorry, I didn't understand the objection before I merged
=> Remove unused CI var

.github/workflows/site-ci.yml, .github/workflows/site-deploy.yml, site/package.json, site/typedoc.json, site/yarn.lock, tsconfig.json
=> fix: site deploy job should fail if yarn build gives errors

src/modules/aws_iam/index.ts
=> fix: allow to delete users with keys or profiles

src/modules/iasql_functions/iasql.ts, src/modules/iasql_functions/index.ts, src/modules/iasql_functions/rpcs/iasql_get_errors.ts, src/modules/iasql_functions/rpcs/index.ts, src/modules/iasql_functions/sql/after_install.sql, src/modules/iasql_platform/entity/index.ts, src/modules/iasql_platform/migration/1670880297247-iasql_platform.ts
=> Save `iasql_commit` and `iasql_rollback` errors on `iasql_audit_log`

src/modules/iasql_functions/sql/after_install.sql
=> Manually close transaction if pg_cron commit failed

site/docusaurus.config.js
Signed-off-by: Yolanda Robla <yolanda@iasql.com>
=> fix: add sidebar by default on SQL reference

test/modules/aws-vpc-routetable-integration.ts
=> Fix availability zone selection

.github/workflows/ci.yml, .github/workflows/develop.yml, .github/workflows/django.yml, .github/workflows/docs-version.yml, .github/workflows/drop.yml, .github/workflows/main.yml, .github/workflows/prisma.yml, .github/workflows/site-ci.yml, .github/workflows/site-deploy.yml, .github/workflows/version.yml
This small PR adds a bit of consistency to our workflows. Open to suggestions.
=> Rename gh workflows

test/modules/aws-lambda-integration.ts, test/modules/aws-vpc-integration.ts
=> Fix pattern picking availability zones in tests

site/package.json
Renamed Table to Method. Removed Columns empty header.
=> bump docusaurus dep, to fix rpc render issues

Dockerfile
Reorder the sequence of commands to put the most stable commands at top. This will dramatically reduce build time during development time by taking advantage of the cache.
=> optimized Dockerfile

.github/workflows/ci.yml, .github/workflows/django.yml, .github/workflows/prisma.yml
This uses a third party action to allow retries. Set autoretry to 1, only if there is an error. Added that for actions that are prone to failure.
Closes: #1731
=> feat: enable autoretry of tests once

postmortems/002 - Postmortem for v0.0.23 release.md
=> Postmortem for v0.0.23 release

.github/workflows/ci.yml, src/modules/aws_vpc/mappers/nat_gateway.ts, src/modules/subscribers.ts, test/modules/aws-s3-integration.ts
=> Update `undefined`s before save

src/modules/aws_ecr/entity/repository_image.ts, src/modules/aws_ecr/index.ts, src/modules/aws_ecr/migration/1673970653263-aws_ecr.ts, test/modules/aws-ecr-integration.ts
Most of this PR revolves around changing the list private repository images client call to the same one used for public repository images which has a different data structure
=> add repo image size and date

.github/workflows/ci.yml, .github/workflows/django.yml, .github/workflows/prisma.yml
Switch to lambda function hosted in bootstrap account
Closes: #1797
=> fix: update lambda function to url to use the one from bootstrap

src/modules/aws_ecr/entity/repository_image.ts, src/modules/aws_ecr/migration/1674643055346-aws_ecr.ts
=> Handle duplicate column in repository image schema

site/docusaurus.config.js, site/package.json, site/src/css/pricing.css, site/src/pages/pricing.mdx, site/src/theme/NavbarItem.js, site/yarn.lock
=> add pricing page

.github/workflows/production.yml
=> Use the deploy tag in build-and-push if specified

src/modules/interfaces.ts
*DataGrip doesn't show the hints until you use the above syntax 🤔*
=> Add enums for method names in `invoke_*` functions

.github/workflows/ci.yml, src/modules/aws_acm/mappers/certificate.ts, src/modules/aws_ecs_fargate/mappers/cluster.ts, src/modules/aws_ecs_fargate/mappers/service.ts, src/modules/aws_ecs_fargate/mappers/task_definition.ts, src/modules/iasql_functions/rpcs/iasql_install.ts
=> Initial approach to reduce install times

src/modules/aws_elb/mappers/target_group.ts
=> Parallelize multi region read

Dockerfile, Dockerfile.dev, dashboard/run/src/config/dev.ts, dashboard/run/src/config/index.ts, dashboard/src/config/dev.ts, dashboard/src/config/index.ts, docker-entrypoint-dev.sh, docker-entrypoint.sh
- Keep `dev` up-to-date
- Better Dockerfile formatting
- Reorder some commands for better performance
- Now wait for engine to be ready before starting the dashboard
=> Dockerfile updates

.github/workflows/release-dockerhub.yml, .yarnrc, Dockerfile, dashboard/.yarnrc
- Modify the dockerfile to cross-build locally
- This may be all that is necessary to get lots of useful cross builds done
=> Docker cross-build support

dashboard/src/components/AppProvider.tsx, dashboard/src/components/IasqlEditor.tsx, dashboard/src/components/QuerySidebar/QuerySidebar.tsx, dashboard/src/components/QuerySidebar/Schema.tsx, dashboard/src/components/common/Accordion.tsx, dashboard/test/querySidebar.spec.ts
=> Select tables with rows

dashboard/src/components/QuerySidebar/Modules.tsx, src/modules/iasql_functions/iasql.ts, src/modules/iasql_functions/rpcs/iasql_uninstall.ts, src/services/db-manager.ts, test/modules/aws-account-integration.ts
=> List the iasql_platform tables in the Schema

site/package.json, site/sidebars.js, site/typedoc.json, src/modules/iasql_platform/entity/index.ts, src/modules/iasql_platform/index.ts, test/common/all-modules-have-tables.ts, test/common/get_sql_since.ts
=> feat: add support for iasql_platform in documentation

dashboard/src/components/QuerySidebar/Schema.tsx
=> [dashboard] Update select table icon

site/blog/updates/beta.md
currently it shows a headshot of the first author
=> change preview image for beta blog post

.github/workflows/build-arch.yml
Confirming success for 0.1.1 https://github.com/iasql/iasql/actions/runs/4285810685/jobs/7464568121
=> Increase docker run step timeout

dashboard/src/components/common/Tab.tsx
=> Fix clickable area on tab's close button

dashboard/src/components/Connect.tsx, dashboard/src/components/common/Wizard.tsx, dashboard/test/connect.spec.ts
=> Disable back on connect wizard

dashboard/src/components/IasqlEditor.tsx, dashboard/src/components/QuerySidebar/Schema.tsx, dashboard/src/components/providers/AppProvider.tsx, dashboard/test/querySidebar.spec.ts
Resolves #2084 
Before:
After:
=> Adapt sidebar functions to new per module structure

dashboard/src/components/DatabaseManagement/DatabaseActions.tsx, dashboard/src/components/DatabaseManagement/DatabaseSelection.tsx, dashboard/src/components/IasqlEditor.tsx, dashboard/src/components/QueryResult.tsx, dashboard/src/components/common/Dropdown.tsx, dashboard/src/components/common/Tab.tsx, dashboard/src/components/providers/AppProvider.tsx, dashboard/test/helper.ts, dashboard/test/queryTabs.spec.ts
=> Enable parallel queries between tabs a track their responses

dashboard/src/pages/api/run.ts
=> Make sure the connection name is not duplicated

dashboard/src/components/DatabaseManagement/DatabaseActions.tsx, dashboard/src/components/providers/AppProvider.tsx, dashboard/src/services/dbApi.ts, src/migration/1669932953007-rpcs.ts, src/router/db.ts, src/services/db-manager.ts, src/services/iasql.ts, src/services/telemetry.ts, test/common/simple-integration.ts
Closes https://github.com/iasql/meta/issues/344
=> Drop export functionality from dashboard and engine

dashboard/src/pages/api/run.ts, src/modules/iasql_functions/iasql.ts, src/services/lazy-dep.ts
Running the IaSQL docker locally spews out a lot of logs that are confusing an irrelevant to anyone not actually developing IaSQL, so this marks them as debug-level (and therefore turned off in the local env)
=> Switch some more logs to debug

site/blog/updates/intro.mdx
=> Add a warning to the intro blogpost

dashboard/src/components/providers/AppProvider.tsx, dashboard/test/install.spec.ts, dashboard/test/uninstall.spec.ts
=> Force run on install and uninstall

dashboard/src/components/QuerySidebar/Schema.tsx
=> fix: add extra truncate class to schema items

dashboard/src/components/QuerySidebar/Schema.tsx, dashboard/src/components/common/Accordion.tsx
Resolves #2114 
Opens in a new tab the module in the docs
=> Add help icon redirecting to docs

dashboard/src/components/DatabaseManagement/DatabaseActions.tsx, dashboard/src/components/Main.tsx, dashboard/src/components/Navbar.tsx, dashboard/src/components/providers/AppProvider.tsx, dashboard/src/services/posthog.ts
=> simplify + properly capture posthog events

dashboard/src/components/IasqlEditor.tsx
=> Fix command initialization

dashboard/src/components/common/ErrorDialog.tsx, dashboard/src/components/providers/AppProvider.tsx, dashboard/test/connectInvalidCreds.spec.ts, dashboard/test/test.list.ts
=> Disconnect on error creating new db

dashboard/src/pages/api/run.ts, dashboard/test/disconnect.spec.ts
=> Handle connection interruptions

src/modules/iasql_functions/rpcs/iasql_uninstall.ts
=> Update transaction hooks for `iasql_uninstall`

dashboard/src/components/DatabaseManagement/DatabaseActions.tsx, dashboard/test/disconnect.spec.ts, dashboard/test/disconnectAll.spec.ts, dashboard/test/theButtonNewDb.spec.ts, dashboard/test/theButtonNewDbCleanAccount.spec.ts
=> Extract disconnect button from dropdown

dashboard/src/components/IasqlEditor.tsx
=> Update editor autocomplete

dashboard/src/components/QuerySidebar/Modules.tsx, dashboard/src/components/QuerySidebar/Schema.tsx, dashboard/src/components/providers/AppProvider.tsx
=> Make required fields bold in sidebar Schema

site/blog/tutorials/optimize-s3-endpoints.mdx
=> Use default max-width for the last image

dashboard/src/components/Connect.tsx, dashboard/src/components/common/Modal.tsx, dashboard/src/components/common/Wizard.tsx
Before connection step:
While connecting:
On error:
=> Don't show the "x" button on DB creation step

README.md, site/docs/getting-started.mdx, site/src/pages/index.jsx
=> make onboarding steps more clear

dashboard/src/components/IasqlEditor.tsx
=> Undo module autocomplete

src/modules/aws_ec2/mappers/registered_instance.ts
I was not able to reproduce but _should_ resolve #2274
=> Ignore instance not found on registered instance

src/modules/iasql_functions/iasql.ts, src/services/telemetry.ts
we already get these through the generic log rpc method
=> rm repeated telemetry events

src/modules/iasql_functions/rpcs/iasql_get_sql_for_transaction.ts, test/common/get_sql_for_transaction.ts
=> Use latest `transactionId` as default for `iasql_get_sql_for_transaction` 

dashboard/src/components/common/Table.tsx, src/modules/iasql_functions/index.ts, src/modules/iasql_functions/rpcs/iasql_create_review.ts, src/modules/iasql_functions/rpcs/index.ts, test/common/create_review.ts
Resolves #2297 
Copying the content here looks like this:
Review description
| action | table_name | id | description |
| --- | --- | --- | --- |
| update | log_group | 4 | quickstart-log-group|us-east-2 |
```sql
UPDATE log_group
SET log_group_name = 'quickstart-log-group', log_group_arn = 'test', creation_time = '2023-01-25T11:17:14.045+00:00', region = (SELECT region FROM aws_regions WHERE region = 'us-east-2')
WHERE log_group_name = 'quickstart-log-group' AND log_group_arn = 'arn:aws:logs:us-east-2:257682470237:log-group:quickstart-log-group:*' AND creation_time = '2023-01-25T11:17:14.045+00:00' AND region = (SELECT region FROM aws_regions WHERE region = 'us-east-2');
```
=> Add `iasql_create_review`

dashboard/src/components/QueryResult.tsx, dashboard/test/query.spec.ts
=> Fix empty query crash

dashboard/src/hooks/useAuth.ts, dashboard/src/pages/index.tsx
the lack of structure here is tripping up one of my PRs
=> clean up auth path

dashboard/test/connect.spec.ts, dashboard/test/connectInvalidCreds.spec.ts, dashboard/test/disconnect.spec.ts, dashboard/test/disconnectAll.spec.ts, dashboard/test/global-setup.ts, dashboard/test/helper.ts, dashboard/test/install.spec.ts, dashboard/test/query.spec.ts, dashboard/test/querySidebar.spec.ts, dashboard/test/queryTabs.spec.ts, dashboard/test/theButtonExistingDb.spec.ts, dashboard/test/theButtonNewDb.spec.ts, dashboard/test/theButtonNewDbCleanAccount.spec.ts, dashboard/test/uninstall.spec.ts
I believe this is dead code since we don't run the suite against staging since we moved to next.js
=> rm dead code

src/modules/iasql_functions/iasql.ts
Debugging another error I realized about this and I think this has more sense. On `commit` we should:
- `apply` only relevant changes
- If that fails, `apply` everything
- If that fails, `revert` changes
- `sync` no matter what happened
- `throw` error if any of the previous steps failed
- If nothing fails, return
=> Only revert on apply failure and then try to sync

.github/workflows/tests-django.yml, .github/workflows/tests-prisma.yml, .github/workflows/tests.yml
=> fix: remove delete protection from leftover db clusters

package.json, src/modules/aws_sdk/index.ts, src/services/aws_macros.ts, yarn.lock
```sql
SELECT * FROM invoke_cloudformation('describeStacks', '{}', 'us-east-2');
```
```json
{
"Stacks": [
{
"StackId": "arn:aws:cloudformation:us-east-2:680703303227:stack/test/4a369bf0-d556-11ed-a7fa-0afe57681d3e",
"StackName": "test",
"Description": "AWS CloudFormation Sample Template LAMP_Single_Instance: Create a LAMP stack using a single EC2 instance and a local MySQL database for storage. This template demonstrates using the AWS CloudFormation bootstrap scripts to install the packages and files necessary to deploy the Apache web server, PHP and MySQL at instance launch time. **WARNING** This template creates an Amazon EC2 instance. You will be billed for the AWS resources used if you create a stack from this template.",
"Parameters": [
{
"ParameterKey": "KeyName",
"ParameterValue": …
```
=> Add `invoke_cloudformation` to `aws_sdk` module

.github/workflows/site-deployment.yml
It was confusingly named before.
=> Revive the site deployment action
