iasql/iasql

src/modules/aws_security_group@0.0.1/index.ts
This *appears* to be working locally, but whatever the race condition is caused by, it must be showing up less frequently on my laptop.
=> Attempted hotfix for the security groups

.module_migration.sh
MacOS uses an ancient version of bash without `readarray` so I replicated the behavior with `sed`
=> Mac-ify the Module migration script

src/modules/aws_account@0.0.1/entity/aws_account.ts, src/modules/aws_account@0.0.1/index.ts, src/modules/aws_cloudwatch@0.0.1/entity/log_group.ts, src/modules/aws_cloudwatch@0.0.1/index.ts, src/modules/aws_ec2@0.0.1/entity/instance.ts, src/modules/aws_ec2@0.0.1/index.ts, src/modules/aws_ecr@0.0.1/entity/aws_public_repository.ts, src/modules/aws_ecr@0.0.1/entity/aws_repository.ts, src/modules/aws_ecr@0.0.1/index.ts, src/modules/aws_ecs_fargate@0.0.1/entity/aws_cluster.ts, src/modules/aws_ecs_fargate@0.0.1/entity/aws_service.ts, src/modules/aws_ecs_fargate@0.0.1/entity/aws_task_definition.ts, src/modules/aws_ecs_fargate@0.0.1/index.ts, src/modules/aws_elb@0.0.1/entity/aws_listener.ts, src/modules/aws_elb@0.0.1/entity/aws_load_balancer.ts, src/modules/aws_elb@0.0.1/entity/aws_target_group.ts, src/modules/aws_elb@0.0.1/index.ts, src/modules/aws_rds@0.0.1/entity/rds.ts, src/modules/aws_rds@0.0.1/index.ts, src/modules/aws_security_group@0.0.1/entity/index.ts, src/modules/aws_security_group@0.0.1/index.ts, src/modules/aws_vpc@0.0.1/entity/index.ts, src/modules/aws_vpc@0.0.1/index.ts, src/modules/interfaces.ts, src/services/cloud-id.ts
Resolves #476
I couldn't make it 100% because one of the entity IDs is based on the unique ID of the entity it joins (which is really weird), but also I realized I would not be able to automate the DB mapper for that entity anyways because it's `read` function is similarly weird. So I'm keeping `entityId` around as a function that is automatically populated if an override is not provided.
=> Switch to a declarative entity ID by default

src/entity/operation.ts, src/migration/1647526647810-init.ts, src/services/scheduler.ts, test/modules/aws-account-integration.ts, test/modules/aws-ec2-integration.ts
add `iasql_plan` and overload the `iasql_install` sp so that it can also be called with just a `text` argument. without this one needs to always pass an array even if it only has one `text` element in it.
before: `call iasql_install(array['aws_vpc@0.0.1'])`
now: `call iasql_install('aws_vpc@0.0.1')`
=> add plan sp and overload (un)install sp

src/modules/aws_account@0.0.1/index.ts, src/modules/aws_cloudwatch@0.0.1/index.ts, src/modules/aws_ec2@0.0.1/index.ts, src/modules/aws_ecr@0.0.1/index.ts, src/modules/aws_ecs_fargate@0.0.1/index.ts, src/modules/aws_elb@0.0.1/index.ts, src/modules/aws_rds@0.0.1/index.ts, src/modules/aws_security_group@0.0.1/index.ts, src/modules/aws_vpc@0.0.1/index.ts, src/modules/interfaces.ts
This is the first half of #478
The second half is automating the `entities` field (will be in a separate PR
=> Automate the population of the 'tables' and 'functions' fields in the 'provides' sub-object

src/modules/aws_account@0.0.1/index.ts, src/modules/aws_cloudwatch@0.0.1/index.ts, src/modules/aws_ec2@0.0.1/index.ts, src/modules/aws_ecr@0.0.1/index.ts, src/modules/aws_ecs_fargate@0.0.1/index.ts, src/modules/aws_elb@0.0.1/index.ts, src/modules/aws_rds@0.0.1/index.ts, src/modules/aws_security_group@0.0.1/index.ts, src/modules/aws_vpc@0.0.1/index.ts, src/modules/interfaces.ts, src/services/iasql.ts, src/services/mod-sort.ts, src/services/scheduler.ts, src/services/typeorm.ts, test/common/dep-sorting.ts
Resolves #478
This also eliminates the path where custom `install` and `remove` functions can be provided outside of the TypeORM migration path, as TypeORM is now 100% required for our modules.
=> Automate the entities list for modules

src/config/config.ts, src/config/test.ts, src/index.ts, src/modules/aws_ecr@0.0.1/index.ts, src/modules/aws_ecs_fargate@0.0.1/index.ts, src/modules/interfaces.ts, src/router/db.ts, src/services/iasql.ts, src/services/logger.ts, test/common/simple-integration.ts, test/helpers.ts
Debugging what's going wrong with a test is hard right now because Jest's console.log takeover code makes it ridiculously hard to read the log output. So I've bypassed it using `process.[stdout|stderr].write` directly. Just take a look at the log output of the tests in *this* PR to see the massive improvement
=> Better test logging

.module_migration.sh, src/config/index.ts, src/index.ts, src/modules/iasql_platform@0.0.1/migration/1649298097680-iasql_platform.ts, src/scripts/list-deps.ts, src/scripts/migrate-dep-order.ts
This updates `gen-module` to use our own logic for module ordering and runs the migrations in that order.
Despite that, there's still some weirdness with `iasql_platform` that I have been able to confirm happens even using TypeORM's migration run and generate code the "proper" way when I blew away all modules besides that one and `aws_account` and *still* got weird pollution from it. It appears to be a regression of some sort in TypeORM because it didn't happen before. I'm thinking of making a simple repo to minimally reproduce the issue and reporting it to TypeORM so I can hopefully remove the weird hackery in my scripts around the `iasql_platform` module.
=> Fix gen-module by running migrations in dep order ourselves

src/services/repositories/metadata.ts, test/common/metadata.ts, test/helpers.ts
This also fixes an error in the scheduler bootstrapping in which it doesn't find already disconnected databases as described in the metadata repo.
=> properly remove db from metadatarepo on disconnect

src/services/iasql.ts
Tested with the new module management UI in the dashboard
=> Exclude all three 'special' modules from listing so you can't (easily) accidentally break your database

src/config/production.ts, src/router/graphql.ts
Before landing my dashboard change to allow module management in the GUI, I deployed the branch to staging and noticed that I could crash the engine, so this is the fix.
- Fix sslmode for postgraphile
- Enable in production now that it was verified with staging
=> Fixes for postgraphile in staging, and enable production

src/services/gateways/aws.ts, src/services/iasql.ts, src/services/typeorm.ts, test/modules/aws-route53-hosted-zones-integration.ts
I realized that I had accidentally left some debug logs in one of my PRs, so I decided to remove them, but I also noticed a few legacy uses of `console.log` where it doesn't belong and fixed that. (The only places `console.log` should be allowed is in the `logger.ts` file which should be relatively obvious, and in the `scripts` as those files unfortunately cannot have a dependency on the `config`, at least at the moment)
=> Remove console.log from where it doesn't belong

src/config/config.ts, src/config/local.ts, src/config/production.ts, src/config/staging.ts, src/config/test.ts, src/modules/index.ts, src/router/index.ts
As discussed offline, this change lets us deploy production without releasing the in-development modules for end users, but lets us do so in the staging environment for end-to-end testing.
=> Make the latest module version configurable

src/modules/0.0.3/aws_security_group/index.ts, src/modules/interfaces.ts
Resolves #715 
It was failing because the interface was returning `undefined` the first time while a parallel job was actually reading from cloud. The security group was not mapped correctly and the the security group rule had no security group assigned.
=> Fix security group mapper

src/modules/0.0.3/aws_cloudwatch/index.ts, src/modules/0.0.3/aws_ec2/index.ts, src/modules/0.0.3/aws_ecr/index.ts, src/modules/0.0.3/aws_ecs_fargate/index.ts, src/modules/0.0.3/aws_elb/index.ts, src/modules/0.0.3/aws_iam/index.ts, src/modules/0.0.3/aws_rds/index.ts, src/modules/0.0.3/aws_route53_hosted_zones/index.ts, src/modules/0.0.3/aws_security_group/index.ts, src/services/gateways/aws.ts, src/services/iasql.ts
Despite some issues in reproducing some error conditions we've seen recently, most of them were caused by hitting the AWS API rate limiter, and that should only be possible by making API requests in parallel.
`Promise.all` requires an array of promises to `await` on, but for those promises to all be created they must have been kicked off, and therefore they're operating in parallel with each other. On top of that, this parallelization can cause double-requests (or more) for resources that aren't in our cache yet since the check for the resource happened before any of the requests responded. By switching to `for-await` loops instead, we linearize the code more, which should prevent the rate limiting errors (I hope) but also reduce wasteful duplicate queries by increasing the cache hit …
=> Don't 'Promise' more than you can handle

test/modules/aws-security-group-integration.ts
The prior bug in the security group module we believe was resolved by #731 but we were unable to reproduce it.
We still want to keep this test because it does a good job of stressing the security group mappers.
=> Write a test to stress-test the security group module

src/scripts/list-deps.ts, src/scripts/migrate-dep-order.ts, src/scripts/module-json-utils.ts, src/services/logger.ts, test/helpers.ts, tslint.json
Minor cleanup PR. Disables usage of `console.log` and friends except in the scripts directory (because weird circular dep issues when using code that creates code) and within our logger definition itself.
=> Only use the logger (except when absolutely necessary to avoid)

src/modules/0.0.4/iasql_functions/sql/create_fns.sql, src/modules/0.0.4/iasql_functions/sql/drop_fns.sql, src/modules/0.0.4/iasql_platform/entity/index.ts, src/modules/0.0.4/iasql_platform/migration/1652392022919-iasql_platform.ts, src/scripts/migrate-dep-order.ts, src/services/iasql.ts
- Add the new 'iasql_audit_log' table to the platform and fix the module migration generation to require zero config changes to run
- Write the audit trigger function and attach/detach it on install/uninstall
- Syntax fixes for the trigger function
=> Add an audit log

src/index.ts, src/services/iasql.ts, src/services/repositories/metadata.ts, src/services/scheduler-api.ts, src/services/scheduler.ts
- Convert the graphile worker scheduler into a child process
- We no longer have a single singleton for the metadata database access
=> Move the graphile workers into a child process

src/modules/0.0.6/aws_ec2/index.ts, test/modules/aws-ec2-integration.ts
Right now if you create an instance and do not defined security groups it enters into a loop trying to stabilize. The `default` security group is added by AWS if no security group was defined. We need to update the database properly based on the newly created cloud object to avoid this looping.
=> Fix looping when no security group defined on EC2

src/migration/1654085956512-update-iasql-user-databases-constraint.ts
While working on #811 I've found there was a missing migration that have not been created yet. I suspect it belongs to [this change](https://github.com/iasql/iasql-engine/commit/e01798a4efbd62a9d50d8ca6866f8546d19620fe)
=> Add missing migration

src/modules/0.0.8/aws_acm_import/index.ts, src/modules/0.0.8/aws_acm_import/module.json
Resolves #764 
Remove unnecessary dependency that could lead to a broken state of the database.
This is because is more a "support" module than a real dependency. `aws_acm_import` could work perfectly without having `aws_acm_list`installed since there are no database relationships between them. They just share some cloud logic.
=> Remove `aws_acm_list` dependency from `aws_acm_import`

src/services/repositories/metadata.ts, src/services/telemetry.ts
in the new data model for analytics, we are tracking the user as the database so the register event is simply the connect event. the metadata repository still preserves the information
=> remove register event

src/services/db-manager.ts, src/services/iasql.ts
I am not entirely sure why this change breaks the disconnect flow, but I have confirmed locally that this fixes it (by simply reverting the behavior in the disconnect flow only)
=> Fix the disconnect regression

src/config/ci.ts, src/config/local.ts, src/config/production.ts, src/config/staging.ts, src/config/test.ts, src/services/db-manager.ts, test/modules/aws-account-integration.ts
Resolves #860
Also fixes an issue with creating a new database with the wrong migrations if the `latest` variable in the Modules export doesn't match `latestVersion` in the environment in question.
TODO: Eliminate all uses in the codebase of the `latest` export, though the rest *probably* aren't as big of a deal.
=> Verify disconnect works for old and busted databases

.github/workflows/ci.yml, package.json, src/modules/0.0.9/aws_elb/entity/listener.ts, src/modules/0.0.9/aws_elb/index.ts, src/modules/0.0.9/aws_elb/migration/1655822977761-aws_elb.ts, src/services/gateways/aws_2.ts
The test suite is getting hanged up sometimes because the engine workers keep trying to connect with the database that is already down. Here is an example:https://github.com/iasql/iasql-engine/runs/6981051342?check_suite_focus=true#step:5:5695
We have to look deeper in that error, but for now we force jest to exit so we avoid long running tests that already failed.
Also, ignore some misconfigured resources instead of throwing an error.
=> Force test exit and do not error on misconfigured resources

src/router/db.ts, src/services/scheduler.ts, src/services/telemetry.ts
this fixes the bug we were seeing were the wrong `string` was used as an argument to the telemetry method
this PR also changes stops sending `runSql` user errors to sentry
=> type and simplify telemetry api

src/modules/0.0.11/aws_security_group/index.ts
I have noticed since the security group AWS client was converted it has become less stable. I don't know why as nothing logically changed with the AWS query logic, but I spotted one place where we don't check the output correctly, so I have added a guard there, which will hopefully fix the stability problems we're seeing.
=> Improve security group stability

src/services/iasql.ts, test/modules/aws-account-integration.ts
It was discovered that TypeORM's `query` method breaks if there are multiple SQL statements in the query. They are run correctly, but no response is returned, as it must not be able to handle the response provided by the postgres driver. So this PR just uses the `pg` library directly and does some light formatting to make the response more closely match the behavior of the `query` function before, which is also generally more intuitive than the metadata-filled objects `pg` returns by default.
=> Add proper support for multiple query statements

package.json, src/services/scheduler.ts
Resolves #896 and surfaces errors to sentry for all iasql functions which were not getting surfaced.
=> initialize sentry within the scheduler child processes

.github/workflows/release.yml
Based on my reading of: https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs I think this is what I did wrong with this trigger before
=> Attempt to fix the doc generation trigger

src/services/iasql.ts
The engine provided a useless empty set when running non-SELECT commands before. The new logic detects this scenario and returns the affected record count in the same form as a query result, instead, to be more useful to end-users.
This resolves iasql/dashboard#147
This also resolves iasql/dashboard#171
=> Fix the response output when executing insert/update/delete sql commands

src/modules/0.0.14/aws_ec2/migration/1657324109020-aws_ec2.ts, src/modules/0.0.14/aws_ec2/sql/create_custom_constraints.sql
While reading through the code to see how to add custom constraints for the load balancer entity, I realized that the custom constraints in the EC2 module had been accidentally dropped in a migration a couple of versions ago, so this restores that back.
=> Restore custom constraints to ec2 module

src/services/iasql.ts
This is an advisory PR only. With the dashboard fixed, I am removing the filter that blocked access to the DynamoDB module.
=> Remove restriction on 'aws_dynamo'

src/modules/0.0.16/aws_account/index.ts, src/modules/0.0.16/aws_ecs_simplified/index.ts, src/modules/interfaces.ts
Part of #862 
The first step in switching to a class-based module system. Proposed new base class and implementation in the AwsAccount module. This conversion *should* work in a piecemeal basis as I made sure the new `ModuleBase` base class implements the `ModuleInterface` interface, but we'll let the test suite decide that. ;)
This is called "Part 1" not just because it's an incomplete conversion, but because there may be further changes/mutations to the pattern shown in this PR. The elimination of `utils` and `mappers` (sorta on the latter) flattens things and should improve Typescript's ability to infer type info, but if there are other [Mapper Footguns](https://github.com/iasql/docs/blob/bd7d9b7ac9af1fc4db3066131c56c61a1f8dd34b/docs/reference/apply_and_sync.md) that I can eliminate …
=> Class-Based Modules, Part 1

.github/workflows/module-cleanup.yml
It shouldn't have used the undocumented function.
=> Fix the cleanup script

src/modules/0.0.16/iasql_functions/index.ts, src/modules/0.0.16/iasql_platform/index.ts, src/services/db-manager.ts, src/services/iasql.ts, src/services/scheduler.ts, src/services/telemetry.ts
These modules are special versus the rest of them as they are manipulated directly by various `src/services` files, and mostly act as the foundational layer for the useful IaSQL modules, so I converted them in a separate PR to keep this somewhat contained.
Lots of conditional logic in the `src/services` files added that can be removed when this version is the oldest supported version.
=> Migrate the 'iasql_*' modules to the new class approach

package.json, src/modules/0.0.17/aws_account/index.ts, src/modules/0.0.17/aws_s3/index.ts, src/modules/0.0.17/iasql_functions/index.ts, src/modules/0.0.17/iasql_platform/index.ts, src/modules/interfaces.ts, src/services/iasql.ts, yarn.lock
Part of #862. I decided to switch to a simpler module for this first pass, and I made the Mapper also a class, but left the Crud properties mostly alone since there's exactly 1 or 2 of them per mapper, unlike the unknown number of mappers per module.
I attach `this.module` to the Mapper and Crud objects so the methods can get *their instance* of the module by going `this.module.<etc>` and I confirmed it's fully typed by Typescript, so I'm happier with this.
I don't like the `dirname = __dirname` that's required right now, since it's an easy-to-forget line to include, so I added a dependency on `callsite` which let's me get the file information from every line of a stack trace, and use it to find the directory where a module is defined in the new `ModuleBase` base class.
=> Class-ify the S3 module

src/modules/0.0.17/aws_account/index.ts, src/modules/0.0.17/aws_acm_import/index.ts, src/modules/0.0.17/aws_acm_list/index.ts, src/modules/0.0.17/aws_cloudwatch/index.ts, src/modules/0.0.17/aws_dynamo/index.ts, src/modules/0.0.17/aws_ecr/index.ts, src/modules/0.0.17/aws_elb/index.ts, src/modules/0.0.17/aws_iam/index.ts, src/modules/0.0.17/aws_rds/index.ts, src/modules/0.0.17/aws_s3/index.ts, src/modules/0.0.17/iasql_functions/index.ts, src/modules/0.0.17/iasql_platform/index.ts
The new class-based modules don't need to explicitly declare their dependencies anymore, so dropping that from the converted modules.
=> Drop explicit dependency declarations

.dockerignore
- Ignored the `node_modules` dir. Copying this can cause `ERR_DLOPEN_FAILED` error originating from the libraries, due to the inconsistency between the host platform and Linux (Docker). Ref: https://stackoverflow.com/a/29994851/9466794
- Also ignored unneeded files like `dist/`, CI and documentation files
=> Fixed local development bug and ignored unneeded files from docker

.github/workflows/ci.yml
I Improved logging in the CI. As @dfellis confirmed on Friday (26/08/2022), the CI would be aborted given a failure response from the Lambda (because of the `jq` query to which the response is piped). However, there is no way to view the error response from the Lambda (for debugging purposes) without logging into CloudWatch and digging - which could easily take minutes of development time.
I have simply added a way to log the error so we can view it in GH actions directly.
=> Improved logging in CI

test/modules/aws-elasticache-integration.ts
Instead of hardcoding the node type, query the list of
available nodes for this type, and pick the first one on
the list.
Closes: #1194
=> Issue #1194: Select cache node type from an available list

src/services/iasql.ts, src/services/scheduler-api.ts, src/services/scheduler.ts
I didn't find a reason for why we were passing both the `dbId` and the `dbUser` variables to the Scheduler, so I just removed `dbUser` 😄 .
=> Refactor Scheduler functions and add Sentry error logging

src/modules/0.0.19/aws_elasticache/index.ts, test/modules/aws-elasticache-integration.ts
Not all node types are available to be used on elasticache,
and they need to be taken from an api. While the test was using
this workflow for creating the cache, it was not using it
for updating it.
Modify the tests to pick a valid node as well for that test.
=> fix: use an available node type for elasticache update test

.develop.sh, .drop.sh, .github/workflows/ci.yml, .version.sh, docker-entrypoint.sh, src/config/bootstrap.ts, src/config/ci.ts, src/config/local.ts, src/config/production.ts, src/config/staging.ts, src/config/test.ts, src/modules/0.0.20/aws_account/sql/create_triggers.sql, src/services/iasql.ts, test/modules/aws-account-integration.ts, test/upgrade/run-upgrade.sh
The issues fixed:
- `docker-entrypoint.sh` now shows the stdout of the scheduler process for better debugging needs
- `iasql_upgrade` no longer barfs on the `sync` call which left the DB half-upgraded
- `default_aws_region` no longer returns NULL if there are no `aws_regions` records with `is_default = true`
Confirmed with manual testing that was then turned into new unit/integration tests.
=> Several fixes to issues encountered during 0.0.19 deployment attempt

src/modules/0.0.20/iasql_functions/sql/create_fns.sql
Further testing with the `delete_all_records` function showed that it can corrupt the new multi-region setup by deleting records from the `aws_regions` table. The table gets auto-restored, *but* the user's default region selection is lost in the process, so just adding that table to a blacklist for now.
=> Leave the regions alone!

.github/workflows/ci.yml, package.json, scripts/check_changes_in_right_version.sh, src/modules/0.0.16/aws_account/module.json
When working in a module sometimes there is the need to do a rebase and start working on newever version. This can bring rebase problems, such as leaving files in the older module. Add a check to prevent it.
Closes: #1283
=> feat: add ci check to detect changes in not current module

examples/ecs-fargate/django/app/app/settings.py
Since the `infra` database is not being used on the target ECS container, I've excluded it when the corresponding environment variables are not available.
=> Tune Django example: Add the checks to prevent container from exiting on ECS

src/modules/0.0.17/aws_security_group/index.ts, src/modules/0.0.18/aws_security_group/index.ts, src/modules/0.0.21/aws_security_group/index.ts, src/modules/0.0.22/aws_security_group/index.ts
As part of figuring out why https://github.com/iasql/iasql-engine/pull/1363 is failing only for security groups, I added some debugging code and realized the memo-access line accidentally changed the type from an object to an array.
Logging showed that some of the object keys were numeric and some were strings, and most security group rules were duplicated, one with a numeric-cast-to-string key and one with the correct key, so I thought it was an accidental misuse of the array type at first, like this:
```js
damocles@zelbinion:~/alantech/iasql-engine(delete-broken-code)$ node
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> const val = ['foo', 'bar'];
undefined
> val.foo = 'foo';
'foo'
> val.bar = 'bar';
'bar'
> console.log(val)
[ 'foo', 'bar', foo: 'foo', bar: 'bar' ] …
```
=> Delete broken code

.github/workflows/ci.yml
While we are partially migrated from single-region to multi-region, the cleanup script can break if a multi-region module is installed and has dependencies in another region that is managed by a single-region module.
This PR disables all regions but the default region to effectively make the multi-region modules behave like they were single region for the purposes of test account cleanup. Once we have multi-region fully implemented, this can be removed, along with other logic like selecting a region at all (which can be moved into the tests themselves and simplify the CI harnesses)
=> Clean only the selected region

src/modules/0.0.22/aws_iam/index.ts, test/modules/aws-iam-integration.ts
The current check to know if we needed to create an instance profile was just looking at service.ec2 as string. But it can also be passed as an array so we also need to do this comparison
Closes: #1368
=> fix: allow comparison for strings and arrays on ec2 profiles

src/modules/interfaces.ts, test/common/all-modules-have-tables.ts
The problem: SQL-only modules like `aws_ecs_simplified` does not correctly handle the tables and functions that should be  provisioned. As a consequence, after module installation, the module was not listed in `iasql_tables`.
The result after installing the module successfully in main branch:
How the schema looks like after installation in main branch:
The result after installing the module successfully in this branch:
How the schema looks like after installation in this branch:
Resolves #1424
=> Handle tables and functions provisioned by sql-only modules

src/modules/0.0.22/aws_route53_hosted_zones/index.ts
Not sure why [this error](https://github.com/iasql/iasql-engine/actions/runs/3335780686/jobs/5521185700) is intermittent, it might be a race condition, but sometimes we ignore some records that should have been there. Why? Because AWS prepends a `dualstack.` string to the load balancer DNS if it is from the same account and the type is `application` (or classic but we do not handle those).
Note from [AWS Docs](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html):
> The console prepends dualstack. to the DNS name of the application and Classic Load Balancer from the same AWS account only. When a client, such as a web browser, requests the IP address for your domain name (example.com) or subdomain name (www.example.com), the client can request an IPv4 …
=> Handle application elb dns on route53 alias target

src/services/aws_macros.ts
After reading through the entirety of the v0.0.21 and v0.0.22 acm modules, I can find zero changes that should impact the ability of Certificate.cloud.read to function correctly. Therefore I am presuming this is an upstream problem and I am attaching the "slow waiter retry" logic we use for AWS's crappier APIs. It seems to work locally, but let's see what the full CI says.
=> Stabilize the ACM tests

docs/blog/2021-09-14-intro.mdx, docs/blog/2022-04-14-os.mdx, docs/blog/authors.yml, docs/docs/how-to/aws.md, docs/docusaurus.config.js, docs/src/css/custom.css, docs/src/pages/index.jsx, docs/src/theme/NavbarItem.js, docs/static/CNAME, docs/versioned_docs/version-0.0.17/how-to/aws.md, docs/versioned_docs/version-0.0.18/how-to/aws.md, docs/versioned_docs/version-0.0.20/how-to/aws.md, docs/versioned_docs/version-0.0.21/how-to/aws.md
porting over the landing page to docusaurus using react + [infima](https://infima.dev/) wasn't too bad. there are a few outdated things in the current landing page, but I figured I would port it as-is and then change it in follow up PRs. the dark mode doesn't work as nicely, but that can also be follow ups
=> merge all webcontent into one docusaurus instance

src/modules/0.0.22/aws_s3/mappers/bucket.ts
Since the code assumes it can continue without a `location` set and uses a default, just catching the potential error here and letting it continue.
=> Attempt to fix the new S3 cleanup failure

src/services/logger.ts
There was a weird blip today with staging and production where they both restarted because of LogDNA errors escaping to the top of the event loop. LogDNA failures are not a fatal problem for the engine itself, so let's capture it and log them to CloudWatch if encountered, as pointed out here: https://github.com/logdna/logger-node/issues/24#issuecomment-712169987 by @aguillenv
=> Catch LogDNA errors

src/scripts/pg_hba.conf
The permissions were too strict for `pg_cron` to work, before. Opening them up only for localhost connection (when pg_cron connects to itself within the docker container) resolves it.
=> Fix continuous mode in singular docker container

.github/workflows/ci.yml
This is going to make CI faster because instead of using `upload-artifact` and `download-artifact` (which treat the image as a BLOB), we'll be uploading the image to the Github container registry which does not upload the layers that already exist and therefore the time of uploading the artifact will be significantly reduced.
=> Push to Github Container Registry instead of using artifacts

.github/workflows/ci.yml, test/common/basic-db.ts
The common tests now take ~20 minutes to run, when successful, so splitting these tests into parallel runs should buy us test run wins.
=> Split the common tests

src/modules/aws_lambda/mappers/lambda_function.ts
Example failure:
https://github.com/iasql/iasql-engine/actions/runs/3666393565/jobs/6198087937#step:7:13301
Happens in LambdaFunction `cloud.delete` when the role does not exist in the database. I initially added `e.role?.arn` and then tried to use the cloud entity value instead.
=> Try to fix CI fails in lambda delete

src/modules/aws_ecr/index.ts
```ts
export class RepositoryPolicy {
...
@OneToOne(() => Repository, { nullable: false, eager: true })
@JoinColumn([
{
name: 'repository_id',
referencedColumnName: 'id',
},
// we defined this one to make sure we are using the right region
{
name: 'region',
referencedColumnName: 'region',
},
])
repository: Repository;
...
}
```
It has `nullable: false`. So all `repositoryPolicy` objects related to a repository should be first deleted in order for it to be deleted from the database. Therefore that additional read/delete is redundant and can be deleted.
=> Remove the redundant delete because it's an impossible case

site/docusaurus.config.js, site/src/theme/DocBreadcrumbs/index.js, site/src/theme/DocBreadcrumbs/styles.module.css
As the content of sql reference is generated dynamically, it has no breadcrumbs. Modify the theme, to provide default breadcrumbs if none is set
=> Add custom breadcrumbs in theme

src/config/config.ts, src/config/test.ts, src/services/aws_macros.ts, test/functional/aws-error-jest.ts, test/functional/aws-error-without-jest.ts
Jest [has issues](https://github.com/facebook/jest/issues/11808) with `instance of` calls. And the AWS SDK is using `instanceof Error` and `instanceof Object` to check the error object in order to decide whether it should do a retry on API error or not.
As a result we see errors in CI tests [not being retried](https://github.com/iasql/iasql-engine/actions/runs/3675331590/jobs/6215623047#step:9:423) and causes jobs to fail.
https://backend.cafe/should-you-use-jest-as-a-testing-library
https://github.com/aws/aws-sdk-js-v3/issues/4273
=> Fix the retry bug in Jest tests

.version.sh
It was a simple copy-paste mistake from .develop.sh
=> Fix the release .version.sh script

src/router/db.ts, src/services/iasql.ts, src/services/logger.ts, src/services/repositories/metadata.ts, src/services/typeorm.ts, test/common/basic-db.ts, test/helpers.ts
Digging through memory dumps and this appears to be ~50% of our "memory leak" because `console.log` holds on to the objects passed to it *forever* for whatever dumb reason.
=> Don't let `console.log` format objects and don't use TypeORM `ConnectionManager`

dashboard/run/yarn.lock
Found out that the exact version of this library we use in the `run` service doesn't work on ARM64, but the next patch release that we coincidentally installed in the `engine` *does* work. Manually copying the `yarn.lock` data from the engine to the run service fixes the Docker container on ARM64 machines.
=> Manually update libpg-query for 'run' service

src/modules/iasql_functions/sql/after_install.sql
I noticed while working on other things last night that `iasql_help` still referred to an `iasql_upgrade` function that hasn't existed for a few releases now.
We should also see about potentially automating the output here so it can also include the RPCs from other modules if/when installed.
=> Remove reference to 'iasql_upgrade' function from 'iasql_help'

src/config/local.ts
This was meant to handle multi-user environments and is just a waste of RAM in the local env. (And that apparently matters with Docker on not-Linux)
=> Disable the worker pool in the local environment

.github/workflows/release-dockerhub.yml
Informational only. Only way to test is on `main` :/
=> Drop arm/v7 support because while Docker supports it, it seems Postgres doesn't

.develop.sh, .version.sh
This was noticed in the last release. A minor glitch which should be fixed by these two script changes
=> Keep the three package.json version numbers in sync

dashboard/src/components/QueryResult.tsx
crud operations actually do not return result, but instead return affected_records, so check that before returning empty response
=> fix: do not return empty response when we have affected_records

src/modules/iasql_functions/rpcs/iasql_rollback.ts
=> Rollback should unlock always, even on failure as `iasql_commit`

.module_migration.sh
We're using Postgres 14 within our docker container but building migrations with Postgres 13. Normally shouldn't matter, but in case there's a Postgres 14-only feature we want to use, would be better to keep them in sync
=> Upgrade the module migration postgres to Postgres 14

src/config/local.ts
With the `debug` level disabled secrets should not be shared, but we will get errors reported to us.
Resolves #2185
=> Turn on Mezmo logging in local env

.github/workflows/production.yml, .github/workflows/release.yml, .github/workflows/staging.yml, .github/workflows/tests-all-accounts.yml, .github/workflows/tests-django.yml, .github/workflows/tests-prisma.yml, .github/workflows/tests.yml
Resolve  #2187 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo ::set-output name=version::${VERSION}
```
**TO-BE**
```yml
echo "version=${VERSION}" >> $GITHUB_OUTPUT
```
=> Replace deprecated command with environment file

src/services/logger.ts
It currently emits an error locally because we didn't have a path for logging to mezmo *and* disabling debug logs.
=> Fix local mezmo logging

src/modules/iasql_functions/rpcs/iasql_create_review.ts
=> Escape the `|` symbol in the text inserted into the review tables

dashboard/src/pages/api/run.ts, dashboard/src/server-config/staging.ts
This was not an issue locally because uuids generated locally conformed to the stripe requirements, but the ones generated by auth0 in staging did not
=> remove characters that need encoding from client_reference_id
